config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
    
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("", include("seedstar_casestudy_one.emaillist.urls", namespace="emaillist"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

seedstar_casestudy_one/emaillist/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.views import defaults as default_views

from seedstar_casestudy_one.emaillist.views import (
    DisplayEmailList,
    AddEmail
)

app_name = "emaillist"
urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("list", view=DisplayEmailList.as_view(), name="display"),
    path("add", view=AddEmail.as_view(), name="add"),
]

seedstar_casestudy_one/emaillist/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class EmailList(models.Model):
    name = models.CharField(_("Email Holder's Name"), blank=False, max_length=255)
    email = models.EmailField(_("Email Address"), blank=False, unique=True)

seedstar_casestudy_one/emaillist/forms.py
from django.forms import ModelForm

from .models import EmailList


class EmailListForm(ModelForm):
    class Meta:
        model = EmailList
        fields = ['name', 'email']

seedstar_casestudy_one/emaillist/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView

from .models import EmailList
from .forms import EmailListForm


class DisplayEmailList(ListView):
    model = EmailList
    template_name = "emaillist/display.html"


class AddEmail(CreateView):
    form_class = EmailListForm
    success_url = reverse_lazy("emaillist:display")
    template_name = "emaillist/add.html"

seedstar_casestudy_one/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

seedstar_casestudy_one/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}seedstar casestudy two{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'emaillist:home' %}">Case Two</a>

        <div class="collapse navbar-collapse " id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'emaillist:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'emaillist:display' %}">List Email <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'emaillist:add' %}">Add Email <span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

seedstar_casestudy_one/templates/emaillist/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add Email{% endblock %}

{% block content %}
  <h1>Add Email</h1>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">ADD</button>
      </div>
    </div>
  </form>
{% endblock %}

seedstar_casestudy_one/templates/emaillist/display.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Email List{% endblock %}

{% block content %}
<div class="container">
  <h2>Emails</h2>

  <div class="list-group">
    
      <ul>
            {% for email in emaillist_list %}
            <li>{{ email.name }} => {{ email.email }}</li>
          {% endfor %}
      </ul>
    
  </div>
</div>
{% endblock content %}

seedstar_casestudy_one/templates/pages/home.html
{% extends "base.html" %}

{% block content %}
    <p class="h1 align-middle text-center text-capitalize" style="padding-bottom: 100px">Welcome to the Email Storage Application</p>
    <div class="main">
        <h3 class="text-center">ASSUMPTIONS</h1>
        <p class="text-center text-capitalize small">Below is a list of the assumptions made on this project</p><hr />
        <ul>
            <li>A user of the application should only have one email address</li>
            <li>Admin should be able to access the data through the default django admin dashboard</li>
            <li>Email addresses and their corresponding name will not be associated with any particular user.</li>
            <li>The application will not handle any media file in production.</li>
            <li>Email  addresss should be unique throughout the system</li>
            <li>The database vendor will be used in both developemnt and production</li>
            <li>Scaling up the application should be easy</li>
            <li>The development environment should not be dependent on the developer's system</li>
            <li>I assumed that the code must decoupled enough to enable unit testing</li>
        </ul>
    </div>
{% endblock content %}

seedstar_casestudy_one/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}